apiVersion: v1
kind: Service
metadata:
  name: bigproject-mern-backend
  namespace: production
  labels:
    app: bigproject-mern
    tier: backend
spec:
  ports:
  - port: 5000
    targetPort: 5000
    name: bigproject-backend-port
  selector:
    app: bigproject-mern
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigproject-mern-backend
  namespace: production
spec:
  selector:
    matchLabels:
      app: bigproject-mern
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: bigproject-mern
        tier: backend
    spec:
      containers:
      - name: bigproject-mern-backend
        image: 763416836081.dkr.ecr.ap-southeast-1.amazonaws.com/big-project/backend:2.0
        resources:
          limits:
            memory: 500Mi
            cpu: 100m
          requests:
            memory: 80Mi
            cpu: 50m
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: bigproject-mern-backend
              key: user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bigproject-mern-backend
              key: password
        - name: DATABASE_DATABASE
          value: peopleproduction
        - name: DATABASE_HOST
          value: big-project-rds.ci3om0gen46y.ap-southeast-1.rds.amazonaws.com
        - name: DATABASE_PORT
          value: "3306"
        - name: BASE_URL
          value: "http://production.sosmedpesbuk.web.id"