apiVersion: v1
kind: Service
metadata:
  name: mern-backend
  namespace: staging
  labels:
    app: mern
    tier: backend
spec:
  ports:
  - port: 5000
    targetPort: 5000
    name: backend-port
  selector:
    app: mern
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend
  namespace: staging
spec:
  selector:
    matchLabels:
      app: mern
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: mern
        tier: backend
    spec:
      containers:
      - name: mern-backend
        image: 763416836081.dkr.ecr.ap-southeast-1.amazonaws.com/big-project/backend:1.0
        resources:
          limits:
            memory: 200Mi
            cpu: 100m
          requests:
            memory: 80Mi
            cpu: 50m
        ports:
        - containerPort: 5000
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mern-backend
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mern-backend
              key: password
        - name: DB_DATABASE
          value: people
        - name: DB_HOST
          value: big-project-rds.ci3om0gen46y.ap-southeast-1.rds.amazonaws.com