apiVersion: v1
kind: Secret
metadata:
  name: bigproject-mern-backend
  namespace: staging
  labels:
    app: bigproject-mern
    tier: backend
type: Opaque
stringData:
  user: admin
  password: admin123!